# Change these first
owner: trineedle # Your GitHub username
repo: upptime-stickybomb # Your Github repository name

# Add your sites here
sites:
  - name: Production
    url: https://www.stickybomb.kr
  - name: Stagning
    url: ${{ secrets.STICKYBOMB_STAGE_URL }}

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-stickybomb
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Stickybomb
  introTitle: "**Stickybomb** Uptime status"
  introMessage: 현재 서버의 상태입니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
