# Change these first
owner: trineedle # Your GitHub username
repo: upptime-stickybomb # Your Github repository name

# Add your sites here
sites:
  - name: Production
    url: https://www.stickybomb.kr
  - name: Staging
    url: https://www.stickybomb-dev.kr

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-stickybomb
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Stickybomb
  introTitle: "**Stickybomb** Uptime status"
  introMessage: 현재 서버의 상태입니다.
  navbar:
    - title: Status
      href: /upptime-stickybomb
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: repository
      href: https://bitbucket.org/trineedle/workspace/projects/BLAC

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
